import { PlaceCardProps } from "@/types/placecard";

export const dummyPlaceCards: PlaceCardProps[] = [
  {
    name: "별빛 카페",
    category: "카페",
    point: 50,
    address: "서울특별시 마포구 연남동 223-17",
    visitedDate: "",
    guidebookCount: "3",
  },
  {
    name: "브라운도넛",
    category: "디저트",
    point: 50,
    address: "서울특별시 성동구 서울숲길 12",
    visitedDate: "",
    guidebookCount: "1",
  },
  {
    name: "청춘서점",
    category: "복합문화공간",
    point: 50,
    address: "서울특별시 용산구 이태원로 143",
    visitedDate: "2025-08-11",
    guidebookCount: "5",
  },
  {
    name: "경복궁",
    category: "문화유적",
    point: 50,
    address: "서울특별시 종로구 사직로 161",
    visitedDate: "",
    guidebookCount: "9",
  },
  {
    name: "성산일출봉",
    category: "자연명소",
    point: 50,
    address: "제주특별자치도 서귀포시 성산읍 일출로 284-12",
    visitedDate: "2025-06-18",
    guidebookCount: "7",
  },
  {
    name: "한강공원 망원지구",
    category: "공원",
    point: 50,
    address: "서울특별시 마포구 망원로 467",
    visitedDate: "2025-05-25",
    guidebookCount: "4",
  },
  {
    name: "우도 땅콩아이스크림",
    category: "카페",
    point: 50,
    address: "제주특별자치도 제주시 우도면 우도해안길 123",
    visitedDate: "",
    guidebookCount: "2",
  },
  {
    name: "도쿄라멘",
    category: "음식점",
    point: 50,
    address: "서울특별시 강남구 논현로 78길 13",
    visitedDate: "",
    guidebookCount: "6",
  },
  {
    name: "부산 감천문화마을",
    category: "관광명소",
    point: 50,
    address: "부산광역시 사하구 감내2로 203",
    visitedDate: "",
    guidebookCount: "8",
  },
  {
    name: "남이섬",
    category: "자연·관광",
    point: 50,
    address: "강원특별자치도 춘천시 남산면 남이섬길 1",
    visitedDate: "2025-01-11",
    guidebookCount: "10",
  },
];
