import { Guidebook } from "@/types/guidebook";
import { PlaceCardProps } from "@/types/placecard";

export const dummyGuidebooks: Guidebook[] = [
  {
    gid: "G001",
    title: "서울 도심 도장깨기 여행",
    description:
      "서울의 대표 명소를 도장깨기처럼 즐기는 하루 코스 가이드북입니다.",
    mapImageUrl: "/imgs/maps/seoul.png",
    publishedDate: "2025-01-10",
    createdAt: "2025-01-02",
    updatedAt: "2025-01-15",
    participantsCount: 128,
    rating: 4.7,
    totalPlaceCount: 12,
    visitedPlaceCount: 9,
    point: 220,
    author: { uid: "user-01", nickname: "여행자Jin", level: 14 },
    emoji: "🗺️",
    color: "#4F46E5",
    thumbnailUrl: null,
  },
  {
    gid: "G002",
    title: "부산 해안 절경 탐방",
    description:
      "광안리와 해운대를 중심으로 한 부산 해안 절경과 맛집 코스입니다.",
    mapImageUrl: "/imgs/maps/busan.png",
    publishedDate: "2024-12-22",
    createdAt: "2024-12-01",
    updatedAt: null,
    participantsCount: 92,
    rating: 4.9,
    totalPlaceCount: 10,
    visitedPlaceCount: 10,
    point: 300,
    author: { uid: "user-02", nickname: "부산로컬", level: 21 },
    emoji: null,
    color: null,
    thumbnailUrl:
      "https://media.istockphoto.com/id/517188688/ko/%EC%82%AC%EC%A7%84/%EC%82%B0-%ED%92%8D%EA%B2%BD.jpg?s=1024x1024&w=0&k=20&c=DiXclovmh6FCUoEn59Wb9qqDaB98ixT8dsSpxpwrlZk=",
  },
  {
    gid: "G003",
    title: "제주 해변 마스터 플랜",
    description:
      "제주의 숨은 해변과 전망 좋은 카페를 따라가는 2박 3일 일정입니다.",
    mapImageUrl: "/imgs/maps/jeju.png",
    publishedDate: "2025-02-05",
    createdAt: "2025-01-28",
    updatedAt: null,
    participantsCount: 187,
    rating: 4.8,
    totalPlaceCount: 15,
    visitedPlaceCount: 8,
    point: 250,
    author: { uid: "user-03", nickname: "NomadJin", level: 19 },
    emoji: "🏝️",
    color: "#3AB0FF",
    thumbnailUrl: null,
  },
  {
    gid: "G004",
    title: "경주 역사 기행",
    description: "불국사와 첨성대를 중심으로 고대 신라의 유적지를 탐방합니다.",
    mapImageUrl: "/imgs/maps/gyeongju.png",
    publishedDate: "2024-11-05",
    createdAt: "2024-10-28",
    updatedAt: null,
    participantsCount: 65,
    rating: 4.5,
    totalPlaceCount: 8,
    visitedPlaceCount: 4,
    point: 180,
    author: { uid: "user-04", nickname: "문화유산러버", level: 11 },
    emoji: "🏯",
    color: "#F97316",
    thumbnailUrl: null,
  },
  {
    gid: "G005",
    title: "속초 설악산 국립공원 트래킹",
    description: "자연과 함께하는 설악산의 가을 단풍 등산 코스입니다.",
    mapImageUrl: "/imgs/maps/sokcho.png",
    publishedDate: "2024-10-10",
    createdAt: "2024-09-29",
    updatedAt: "2024-10-12",
    participantsCount: 74,
    rating: 4.6,
    totalPlaceCount: 6,
    visitedPlaceCount: 5,
    point: 210,
    author: { uid: "user-05", nickname: "산속의코더", level: 17 },
    emoji: null,
    color: null,
    thumbnailUrl:
      "https://media.istockphoto.com/id/517188688/ko/%EC%82%AC%EC%A7%84/%EC%82%B0-%ED%92%8D%EA%B2%BD.jpg?s=1024x1024&w=0&k=20&c=DiXclovmh6FCUoEn59Wb9qqDaB98ixT8dsSpxpwrlZk=",
  },
  {
    gid: "G006",
    title: "전주 한옥마을 감성 투어",
    description:
      "한복 체험과 전통음식 투어를 중심으로 한 전주의 감성 여행 코스입니다.",
    mapImageUrl: "/imgs/maps/jeonju.png",
    publishedDate: "2024-09-02",
    createdAt: "2024-08-20",
    updatedAt: null,
    participantsCount: 51,
    rating: 4.4,
    totalPlaceCount: 7,
    visitedPlaceCount: 3,
    point: 160,
    author: { uid: "user-06", nickname: "감성러", level: 8 },
    emoji: "🏮",
    color: "#D946EF",
    thumbnailUrl: null,
  },
  {
    gid: "G007",
    title: "강릉 카페거리 원데이 코스",
    description: "강문해변 근처의 인기 카페와 브런치 맛집 투어입니다.",
    mapImageUrl: "/imgs/maps/gangneung.png",
    publishedDate: "2025-01-02",
    createdAt: "2024-12-20",
    updatedAt: null,
    participantsCount: 102,
    rating: 4.9,
    totalPlaceCount: 5,
    visitedPlaceCount: 5,
    point: 190,
    author: { uid: "user-07", nickname: "CoffeeNomad", level: 25 },
    emoji: null,
    color: null,
    thumbnailUrl:
      "https://media.istockphoto.com/id/517188688/ko/%EC%82%AC%EC%A7%84/%EC%82%B0-%ED%92%8D%EA%B2%BD.jpg?s=1024x1024&w=0&k=20&c=DiXclovmh6FCUoEn59Wb9qqDaB98ixT8dsSpxpwrlZk=",
  },
  {
    gid: "G008",
    title: "인천 차이나타운 반나절 투어",
    description:
      "짜장면의 원조, 인천 차이나타운과 자유공원 일대 맛집 탐방 코스입니다.",
    mapImageUrl: "/imgs/maps/incheon.png",
    publishedDate: "2024-12-12",
    createdAt: "2024-12-01",
    updatedAt: null,
    participantsCount: 33,
    rating: 4.2,
    totalPlaceCount: 6,
    visitedPlaceCount: 2,
    point: 120,
    author: { uid: "user-08", nickname: "EatTourist", level: 9 },
    emoji: "🥟",
    color: "#FACC15",
    thumbnailUrl: null,
  },
  {
    gid: "G009",
    title: "대전 과학 도시 탐험",
    description:
      "국립중앙과학관과 엑스포과학공원을 중심으로 가족과 함께하는 과학 여행 코스입니다.",
    mapImageUrl: "/imgs/maps/daejeon.png",
    publishedDate: "2024-11-11",
    createdAt: "2024-10-30",
    updatedAt: null,
    participantsCount: 46,
    rating: 4.3,
    totalPlaceCount: 9,
    visitedPlaceCount: 6,
    point: 175,
    author: { uid: "user-09", nickname: "과학소년", level: 7 },
    emoji: "🔬",
    color: "#60A5FA",
    thumbnailUrl: null,
  },
  {
    gid: "G010",
    title: "광주 예술의 거리 감상 투어",
    description: "전시관과 공방, 소극장을 중심으로 한 예술 감상 코스입니다.",
    mapImageUrl: "/imgs/maps/gwangju.png",
    publishedDate: "2025-01-20",
    createdAt: "2025-01-05",
    updatedAt: null,
    participantsCount: 58,
    rating: 4.5,
    totalPlaceCount: 8,
    visitedPlaceCount: 3,
    point: 155,
    author: { uid: "user-10", nickname: "ArtLover", level: 13 },
    emoji: null,
    color: null,
    thumbnailUrl:
      "https://media.istockphoto.com/id/517188688/ko/%EC%82%AC%EC%A7%84/%EC%82%B0-%ED%92%8D%EA%B2%BD.jpg?s=1024x1024&w=0&k=20&c=DiXclovmh6FCUoEn59Wb9qqDaB98ixT8dsSpxpwrlZk=",
  },
];

export const dummyPlaces: PlaceCardProps[] = [
  {
    pid: "1",
    name: "별빛 카페",
    category: "카페",
    point: 4.6,
    address: "서울특별시 마포구 연남동 223-17",
    visitedDate: "2025-10-10",
    guidebookCount: "3",
  },
  {
    pid: "2",
    name: "한강공원 망원지구",
    category: "관광명소",
    point: 4.8,
    address: "서울특별시 마포구 망원로 467",
    visitedDate: "2025-09-22",
    guidebookCount: "5",
  },
  {
    pid: "3",
    name: "도쿄라멘",
    category: "음식점",
    point: 4.4,
    address: "서울특별시 강남구 논현로 78길 13",
    visitedDate: "2025-08-30",
    guidebookCount: "2",
  },
  {
    pid: "4",
    name: "롯데월드타워",
    category: "전망대",
    point: 4.9,
    address: "서울특별시 송파구 올림픽로 300",
    visitedDate: "2025-07-15",
    guidebookCount: "8",
  },
  {
    pid: "5",
    name: "북서울미술관",
    category: "전시관",
    point: 4.3,
    address: "서울특별시 노원구 동일로 1238",
    visitedDate: "2025-05-12",
    guidebookCount: "1",
  },
  {
    pid: "6",
    name: "성산일출봉",
    category: "자연명소",
    point: 4.9,
    address: "제주특별자치도 서귀포시 성산읍 일출로 284-12",
    visitedDate: "2025-04-18",
    guidebookCount: "6",
  },
  {
    pid: "7",
    name: "경복궁",
    category: "문화유적",
    point: 4.7,
    address: "서울특별시 종로구 사직로 161",
    visitedDate: "2025-03-05",
    guidebookCount: "9",
  },
  {
    pid: "8",
    name: "오션뷰 펜션 블루웨이브",
    category: "숙소",
    point: 4.5,
    address: "강원도 양양군 현남면 인구길 88",
    visitedDate: "2025-06-09",
    guidebookCount: "2",
  },
  {
    pid: "9",
    name: "제주 흑돼지 거리",
    category: "음식거리",
    point: 4.8,
    address: "제주특별자치도 제주시 연동 123-45",
    visitedDate: "2025-09-02",
    guidebookCount: "4",
  },
  {
    pid: "10",
    name: "부산 감천문화마을",
    category: "관광명소",
    point: 4.9,
    address: "부산광역시 사하구 감내2로 203",
    visitedDate: "2025-10-01",
    guidebookCount: "7",
  },
];
